version: '2'
services:
  php-apache-backend:
    image: 'wascardev/apache-php'
    ports:
      - '80'
    volumes:
      - ./backend:/var/www/html
    networks:
      static-network:
        ipv4_address: 172.27.0.3
  php-apache-frontend:
          image: 'wascardev/apache-php'
          ports:
            - '80'
          volumes:
            - ./frontend:/var/www/html
          networks:
            static-network:
              ipv4_address: 172.27.0.4
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.27.0.1/16
          ip_range: 172.27.0.255/24
          gateway: 172.27.0.255